version: '3.3'
services:
  web:
    build: .
    volumes:
      - ./src:/nino
    ports:
      - 1337:1337
    networks:
      - private
    cap_add:
      - NET_ADMIN
      - NET_RAW
networks:
  private:
    external: false